# Generated by Django 4.0.5 on 2022-11-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
